modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="JourneyMap Entity Bridge"
description='''Shows Immersive Vehicles (MTS), Yuushya and MTR entities as colored markers on the JourneyMap minimap and fullscreen map.'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="journeymap"
mandatory=false
versionRange="[5.9.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="mts"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="yuushya"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mtr"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
